spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/site_publish?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  sql:
    init:
      mode: never

